"""add Maintenance

Revision ID: 9568949aed23
Revises: 
Create Date: 2024-08-05 22:42:58.329182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9568949aed23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('number_robot', sa.Integer(), nullable=False),
    sa.Column('incident', sa.String(), nullable=False),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('name_main_programm', sa.String(), nullable=True),
    sa.Column('coord', sa.String(), nullable=True),
    sa.Column('name_user', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lilwaamernigga',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('maintenance',
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.Column('last_updata_men', sa.String(), nullable=False),
    sa.Column('last_updata_men_sur', sa.String(), nullable=False),
    sa.Column('whot_swap', sa.String(), nullable=False),
    sa.Column('wire_mark', sa.String(), nullable=True),
    sa.Column('wire_diameter', sa.Float(), nullable=True),
    sa.Column('name_gaz', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id_robot', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robotstate',
    sa.Column('id_robot', sa.Integer(), nullable=False),
    sa.Column('wire', sa.Integer(), nullable=False),
    sa.Column('wire_mark', sa.String(), nullable=False),
    sa.Column('wire_diameter', sa.Float(), nullable=False),
    sa.Column('gaz_state', sa.Float(), nullable=True),
    sa.Column('name_gaz', sa.String(), nullable=True),
    sa.Column('tip_data_change', sa.DateTime(), nullable=True),
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.Column('last_updata_men', sa.String(), nullable=True),
    sa.Column('last_updata_men_sur', sa.String(), nullable=True),
    sa.Column('busy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urlsheet',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urlsheet')
    op.drop_table('robotstate')
    op.drop_table('observations')
    op.drop_table('maintenance')
    op.drop_table('lilwaamernigga')
    op.drop_table('incident')
    # ### end Alembic commands ###
