"""add Maintenance

Revision ID: ba8d66487637
Revises: 5ad399f7222f
Create Date: 2024-08-05 22:24:03.156146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8d66487637'
down_revision: Union[str, None] = '5ad399f7222f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('datatime', sa.DateTime(), nullable=True),
    sa.Column('last_updata_men', sa.String(), nullable=False),
    sa.Column('last_updata_men_sur', sa.String(), nullable=False),
    sa.Column('whot_swap', sa.String(), nullable=False),
    sa.Column('wire_mark', sa.String(), nullable=True),
    sa.Column('wire_diameter', sa.Float(), nullable=True),
    sa.Column('name_gaz', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    # ### end Alembic commands ###
